import {Wrapper} from './wrapper/Wrapper'
import { Button } from './button/Button'
import { Title } from './title/Title'
import { Input } from './input/Input'
import { Select } from './select/Select'
import { CalculateLayout } from './calculateLayout/CalculateLayout'
import { OpeningLayout } from './openingLayout/OpeningLayout'
import {Cross} from './svg/Cross'
import {File} from './svg/File'
import { OpeningCard } from './openingCard/OpeningCard'
export {Wrapper,Button,Title,Input,Select,CalculateLayout,Cross,File,OpeningLayout,OpeningCard}